### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by insung** [ultrabolido/PrinceJS#3]
drag & drop index.html to chrome browser or ie browser.

but I can't start this game.

how to run?

**Comment by plissken2013es** [comment]
It's based on Phaser. So you need a "localhost" server (XAMMP or similar) to run it, or you can upload it to a web server if you have one available.

**Comment by insung** [comment]
I installed the xampp server, and the game works well. thank you.
but there seems to be some bugs in the game.
I hope this project to be success.
